__version__ = "0.0.14"
__application_name__ = "bup"
__title__ = __application_name__
__author__ = "abel"
__author_email__ = "j@abel.co"
__author_url__ = "https://www.abel.co"
__url__ = "https://github.com/jamesabel/bup"
__download_url__ = __url__
__description__ = "backup all your AWS S3 buckets and DynamoDB tables, and github repos to a backup directory/folder"
